version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
  server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
             - run:
                 command: npm install
                 working_directory: ./server
             - run:
                 command: npm test
                 working_directory: ./server
  client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
         steps:
           - run:
              command: npm install
              working_directory: ./client
           - run:
              command: npm test
              working_directory: ./client
workflows:
    build-and-test:
      jobs:
        - server
        - client
